name-map:
  ⛔ 广告拦截: adblock
  🚀 选择代理: proxy
  🌐 突破锁区: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - 中转
    - OVERALL
  JP:
    - JP
    - Japan
    - 日
    - 🇯🇵
  US:
    - US
    - United States
    - 美
    - 🇺🇸
  CN:
    - CN
    - China
    - 中国
    - 上海
    - 浙江
    - 广东
    - 深圳
    - 🇨🇳
  HK:
    - HK
    - Hong Kong
    - 港
    - 🇭🇰
  TW:
    - TW
    - Taiwan
    - 台
    - 🇹🇼
  CA:
    - CA
    - Canada
    - 加拿大
    - 🇨🇦
  FR:
    - FR
    - French
    - 法
    - 🇫🇷
  SG:
    - SG
    - Singapore
    - 新加坡
    - 狮城
    - 🇸🇬
  GB:
    - GB
    - UK
    - United Kindom
    - Britain
    - 英
    - 🇬🇧
  KR:
    - KR
    - Korea
    - 韩
    - 🇰🇷
  RU:
    - RU
    - Russia
    - 俄
    - 🇷🇺
  DE:
    - DE
    - Germany
    - 德
    - 🇩🇪
  SE:
    - SE
    - Sweden
    - 瑞典
    - 🇸🇪
  CH:
    - CH
    - Switzerland
    - 瑞士
    - 🇨🇭
  EE:
    - EE
    - Estonia
    - 爱沙尼亚
    - 🇪🇪

categories_disp:
  JP: 🇯🇵 日本
  US: 🇺🇸 美国
  HK: 🇭🇰 香港
  TW: ❔ 台湾
  SG: 🇸🇬 新加坡
  CA: 🇨🇦 加拿大
  FR: 🇫🇷 法国
  GB: 🇬🇧 英国
  KR: 🇰🇷 韩国
  DE: 🇩🇪 德国
  CN: 🇨🇳 中国
  RU: 🇷🇺 俄罗斯
  # SE: 🇸🇪 瑞典
  # CH: 🇨🇭 瑞士
  # EE: 🇪🇪 爱沙尼亚